ublox_base:
  ros__parameters:
    debug: 0                    # Range 0-4 (0 means no debug statements will print)
    device: /dev/ttyUSB1
    frame_id: gps_base
    config_on_startup: false
    uart1:
      baudrate: 460800 #115200
    rate: 5.0
    
    publish:
      all: False

gps: # This is the rover
  ros__parameters:
    debug: 0                    # Range 0-4 (0 means no debug statements will print)
    device: /dev/ttyACM1
    frame_id: gps_link
    config_on_startup: false
    uart1:
      baudrate: 115200
    rate: 5.0
    
    publish:
      all: False
      nmea: False
      nav:
        heading: True
        # relposned: True
        # cov: True
        # status: True